"""Initial migration

Revision ID: 9053024ed10a
Revises:
Create Date: 2024-05-19 03:51:14.944212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9053024ed10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('featured_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key('fk_post_category', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('tags')
        batch_op.drop_column('category_id')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
