"""Add slug to Post

Revision ID: a2bd0f3c3ea5
Revises: 9053024ed10a
Create Date: 2024-05-19 04:51:14.944212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision = 'a2bd0f3c3ea5'
down_revision = '9053024ed10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_post_category', 'category', ['category_id'], ['id'])

    # Populate the new 'slug' column with some default values
    post_table = table('post',
                       column('id', sa.Integer),
                       column('slug', String))

    op.execute(post_table.update().values(slug=sa.func.substr(sa.func.lower(sa.func.replace(sa.column('title'), ' ', '-')), 1, 100)))

    # Alter the 'slug' column to be non-nullable
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category', type_='foreignkey')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
